#pragma once

#define DEVELOPER_MODE 0
#define BEHAVIOUR_CHANGE_FORCE_WINDOW_MODE 0
#define BEHAVIOUR_CHANGE_SUB_DATA_FOLDERS 1
#define AUTO_SWITCH_CONTROLLER 1
#define MISC_PC_MENU_FIXES 1
#define ORIGINAL_PS1_BEHAVIOR 1
#define ORIGINAL_GAME_FIXES 1
#define ORIGINAL_GAME_FIX_AUTO_TURN 0
#define ORIGINAL_GAME_FIX_DEATH_DELAY_AO 0
#define FORCE_DDCHEAT 1
#define LCD_PS1_SPEED 0
#define XINPUT_SUPPORT 0
#define RENDER_TEST 0
#define USE_SDL2 1
#define USE_SDL2_SOUND 1
#define USE_SDL2_IO 1
#define RENDERER_OPENGL 0
/* #undef BUILD_NUMBER */
#define CI_PROVIDER "private\ (local\ build)"
