#!/bin/sh

WORKDIR="$(dirname "$(readlink -f "$APPIMAGE")")"
HERE="$(dirname "$(readlink -f "$0")")"

# cd into the game data directory
cd "$WORKDIR" || exit 1

export LD_LIBRARY_PATH="$HERE/usr/lib:${LD_LIBRARY_PATH:-}"

# $@ will forward AppImage args to the binary
exec "$HERE/usr/bin/relive" "$@"
