#include "BaseGameObject.hpp"
#include "../AliveLibAE/BaseGameObject.hpp"
#include "../AliveLibAO/BaseGameObject.hpp"
#include "../AliveLibCommon/Sys_common.hpp"

ReliveTypes IBaseGameObject::FromAO(AO::AOTypes aoType)
{
    switch (aoType)
    {
        case AO::AOTypes::eNone_0:
            return ReliveTypes::eNone;
        case AO::AOTypes::eAlarm_1:
            return ReliveTypes::eAlarm;
        case AO::AOTypes::eScreenManager_4:
            return ReliveTypes::eScreenManager;
        case AO::AOTypes::eBackgroundAnimation_5:
            return ReliveTypes::eBackgroundAnimation;
        case AO::AOTypes::eBat_6:
            return ReliveTypes::eBat;
        case AO::AOTypes::eLiftMover_7:
            return ReliveTypes::eLiftMover;
        case AO::AOTypes::eTimedMine_8:
            return ReliveTypes::eTimedMine;
        case AO::AOTypes::eBullet_10:
            return ReliveTypes::eBullet;
        case AO::AOTypes::eDDCheat_12:
            return ReliveTypes::eDDCheat;
        case AO::AOTypes::eBells_13:
            return ReliveTypes::eBells;
        case AO::AOTypes::eChimeLock_14:
            return ReliveTypes::eChimeLock;
        case AO::AOTypes::eSpark_15:
            return ReliveTypes::eSpark;
        case AO::AOTypes::eGasClock_16:
            return ReliveTypes::eGasClock;
        case AO::AOTypes::eParticleBurst_19:
            return ReliveTypes::eParticleBurst;
        case AO::AOTypes::eDoor_21:
            return ReliveTypes::eDoor;
        case AO::AOTypes::eBird_22:
            return ReliveTypes::eBird;
        case AO::AOTypes::eGameSpeak_24:
            return ReliveTypes::eGameSpeak;
        case AO::AOTypes::eElectricWall_25:
            return ReliveTypes::eElectricWall;
        case AO::AOTypes::eElum_26:
            return ReliveTypes::eElum;
        case AO::AOTypes::eBellHammer_27:
            return ReliveTypes::eBellHammer;
        case AO::AOTypes::ePalOverwriter_29:
            return ReliveTypes::ePalOverwriter;
        case AO::AOTypes::eBaseBomb_30:
            return ReliveTypes::eBaseBomb;
        case AO::AOTypes::eSecurityClaw_31:
            return ReliveTypes::eSecurityClaw;
        case AO::AOTypes::eRockSpawner_32:
            return ReliveTypes::eRockSpawner;
        case AO::AOTypes::eFlintLockFire_34:
            return ReliveTypes::eFlintLockFire;
        case AO::AOTypes::eThrowableTotalIndicator_35:
            return ReliveTypes::eThrowableTotalIndicator;
        case AO::AOTypes::eFootSwitch36:
            return ReliveTypes::eFootSwitch;
        case AO::AOTypes::eGameEnderController_37:
            return ReliveTypes::eGameEnderController;
        case AO::AOTypes::eDeathBird_38:
            return ReliveTypes::eDeathBird;
        case AO::AOTypes::eLoadingFile_39:
            return ReliveTypes::eLoadingFile;
        case AO::AOTypes::eGrenade_40:
            return ReliveTypes::eGrenade;
        case AO::AOTypes::eGrenadeMachine_41:
            return ReliveTypes::eGrenadeMachine;
        case AO::AOTypes::eBackgroundGlukkon_42:
            return ReliveTypes::eBackgroundGlukkon;
        case AO::AOTypes::eAbe_43:
            return ReliveTypes::eAbe;
        case AO::AOTypes::MainMenuFade_44:
            return ReliveTypes::MainMenuFade;
        case AO::AOTypes::eHoneySack_45:
            return ReliveTypes::eHoneySack;
        case AO::AOTypes::eHoney_47:
            return ReliveTypes::eHoney;
        case AO::AOTypes::eClawOrBirdPortalTerminator_48:
            return ReliveTypes::eClawOrBirdPortalTerminator;
        case AO::AOTypes::eCtorMudokon_52:
            return ReliveTypes::eCtorMudokon;
        case AO::AOTypes::eLiftPoint_51:
            return ReliveTypes::eLiftPoint;
        case AO::AOTypes::SecurityOrb_53:
            return ReliveTypes::SecurityOrb;
        case AO::AOTypes::eMeat_54:
            return ReliveTypes::eMeat;
        case AO::AOTypes::eMeatStack_55:
            return ReliveTypes::eMeatStack;
        case AO::AOTypes::eMeatSaw_56:
            return ReliveTypes::eMeatSaw;
        case AO::AOTypes::eMine_57:
            return ReliveTypes::eMine;
        case AO::AOTypes::eRollingBallStopperShaker_58:
            return ReliveTypes::eRollingBallStopperShaker;
        case AO::AOTypes::eMotionDetector_59:
            return ReliveTypes::eMotionDetector;
        case AO::AOTypes::eRollingBallStopper_60:
            return ReliveTypes::eRollingBallStopper;
        case AO::AOTypes::ePauseMenu_61:
            return ReliveTypes::ePauseMenu;
        case AO::AOTypes::eParamite_62:
            return ReliveTypes::eParamite;
        case AO::AOTypes::eDemoPlayback:
            return ReliveTypes::eDemoPlayback;
        case AO::AOTypes::eBirdPortal_65:
            return ReliveTypes::eBirdPortal;
        case AO::AOTypes::eBirdPortalTerminator_66:
            return ReliveTypes::eBirdPortalTerminator;
        case AO::AOTypes::eFG1_67:
            return ReliveTypes::eFG1;
        case AO::AOTypes::ePullRingRope_68:
            return ReliveTypes::ePullRingRope;
        case AO::AOTypes::eAbilityRing_69:
            return ReliveTypes::eAbilityRing;
        case AO::AOTypes::eRock_70:
            return ReliveTypes::eRock;
        case AO::AOTypes::eRockSack_71:
            return ReliveTypes::eRockSack;
        case AO::AOTypes::eRollingBall_72:
            return ReliveTypes::eRollingBall;
        case AO::AOTypes::eRope_73:
            return ReliveTypes::eRope;
        case AO::AOTypes::eExplosion_74:
            return ReliveTypes::eExplosion;
        case AO::AOTypes::eMudokon_75:
            return ReliveTypes::eMudokon;
        case AO::AOTypes::eRedLaser_76:
            return ReliveTypes::eRedLaser;
        case AO::AOTypes::eScrab_77:
            return ReliveTypes::eScrab;
        case AO::AOTypes::eScreenClipper_78:
            return ReliveTypes::eScreenClipper;
        case AO::AOTypes::eEffectBase_79:
            return ReliveTypes::eEffectBase;
        case AO::AOTypes::eDeathFadeOut_80:
            return ReliveTypes::eDeathFadeOut;
        case AO::AOTypes::eFlash_81:
            return ReliveTypes::eFlash;
        case AO::AOTypes::ScreenShake_82:
            return ReliveTypes::ScreenShake;
        case AO::AOTypes::eScreenWave_83:
            return ReliveTypes::eScreenWave;
        case AO::AOTypes::eUnknown_84:
            return ReliveTypes::eUnknown;
        case AO::AOTypes::eShrykull_85:
            return ReliveTypes::eShrykull;
        case AO::AOTypes::eSnoozParticle_87:
            return ReliveTypes::eSnoozParticle;
        case AO::AOTypes::eSlig_88:
            return ReliveTypes::eSlig;
        case AO::AOTypes::eSlog_89:
            return ReliveTypes::eSlog;
        case AO::AOTypes::SlingMud_90:
            return ReliveTypes::SlingMud;
        case AO::AOTypes::eSligSpawner_91:
            return ReliveTypes::eSligSpawner;
        case AO::AOTypes::eZBall_92:
            return ReliveTypes::eZBall;
        case AO::AOTypes::eParticle_93:
            return ReliveTypes::eParticle;
        case AO::AOTypes::eZapLine_94:
            return ReliveTypes::eZapLine;
        case AO::AOTypes::eBeeSwarm_95:
            return ReliveTypes::eBeeSwarm;
        case AO::AOTypes::eBeeNest_96:
            return ReliveTypes::eBeeNest;
        case AO::AOTypes::eLever_97:
            return ReliveTypes::eLever;
        case AO::AOTypes::eTrapDoor_98:
            return ReliveTypes::eTrapDoor;
        case AO::AOTypes::eUXB_99:
            return ReliveTypes::eUXB;
        case AO::AOTypes::eMovie_100:
            return ReliveTypes::eMovie;
        case AO::AOTypes::eWell_101:
            return ReliveTypes::eWell;
        case AO::AOTypes::eCameraSwapper_102:
            return ReliveTypes::eCameraSwapper;
        case AO::AOTypes::eElectrocute_103:
            return ReliveTypes::eElectrocute;
        default:
            ALIVE_FATAL("Unknown AO type");
    }
    return ReliveTypes::eNone;
}

AO::AOTypes IBaseGameObject::ToAO(ReliveTypes reliveType)
{
    switch (reliveType)
    {
        case ReliveTypes::eNone:
            return AO::AOTypes::eNone_0;
        case ReliveTypes::eAlarm:
            return AO::AOTypes::eAlarm_1;
        case ReliveTypes::eScreenManager:
            return AO::AOTypes::eScreenManager_4;
        case ReliveTypes::eBackgroundAnimation:
            return AO::AOTypes::eBackgroundAnimation_5;
        case ReliveTypes::eBat:
            return AO::AOTypes::eBat_6;
        case ReliveTypes::eLiftMover:
            return AO::AOTypes::eLiftMover_7;
        case ReliveTypes::eTimedMine:
            return AO::AOTypes::eTimedMine_8;
        case ReliveTypes::eBullet:
            return AO::AOTypes::eBullet_10;
        case ReliveTypes::eDDCheat:
            return AO::AOTypes::eDDCheat_12;
        case ReliveTypes::eBells:
            return AO::AOTypes::eBells_13;
        case ReliveTypes::eChimeLock:
            return AO::AOTypes::eChimeLock_14;
        case ReliveTypes::eSpark:
            return AO::AOTypes::eSpark_15;
        case ReliveTypes::eGasClock:
            return AO::AOTypes::eGasClock_16;
        case ReliveTypes::eParticleBurst:
            return AO::AOTypes::eParticleBurst_19;
        case ReliveTypes::eDoor:
            return AO::AOTypes::eDoor_21;
        case ReliveTypes::eBird:
            return AO::AOTypes::eBird_22;
        case ReliveTypes::eGameSpeak:
            return AO::AOTypes::eGameSpeak_24;
        case ReliveTypes::eElectricWall:
            return AO::AOTypes::eElectricWall_25;
        case ReliveTypes::eElum:
            return AO::AOTypes::eElum_26;
        case ReliveTypes::eBellHammer:
            return AO::AOTypes::eBellHammer_27;
        case ReliveTypes::ePalOverwriter:
            return AO::AOTypes::ePalOverwriter_29;
        case ReliveTypes::eBaseBomb:
            return AO::AOTypes::eBaseBomb_30;
        case ReliveTypes::eSecurityClaw:
            return AO::AOTypes::eSecurityClaw_31;
        case ReliveTypes::eRockSpawner:
            return AO::AOTypes::eRockSpawner_32;
        case ReliveTypes::eFlintLockFire:
            return AO::AOTypes::eFlintLockFire_34;
        case ReliveTypes::eThrowableTotalIndicator:
            return AO::AOTypes::eThrowableTotalIndicator_35;
        case ReliveTypes::eFootSwitch:
            return AO::AOTypes::eFootSwitch36;
        case ReliveTypes::eGameEnderController:
            return AO::AOTypes::eGameEnderController_37;
        case ReliveTypes::eDeathBird:
            return AO::AOTypes::eDeathBird_38;
        case ReliveTypes::eLoadingFile:
            return AO::AOTypes::eLoadingFile_39;
        case ReliveTypes::eGrenade:
            return AO::AOTypes::eGrenade_40;
        case ReliveTypes::eGrenadeMachine:
            return AO::AOTypes::eGrenadeMachine_41;
        case ReliveTypes::eBackgroundGlukkon:
            return AO::AOTypes::eBackgroundGlukkon_42;
        case ReliveTypes::eAbe:
            return AO::AOTypes::eAbe_43;
        case ReliveTypes::MainMenuFade:
            return AO::AOTypes::MainMenuFade_44;
        case ReliveTypes::eHoneySack:
            return AO::AOTypes::eHoneySack_45;
        case ReliveTypes::eHoney:
            return AO::AOTypes::eHoney_47;
        case ReliveTypes::eClawOrBirdPortalTerminator:
            return AO::AOTypes::eClawOrBirdPortalTerminator_48;
        case ReliveTypes::eCtorMudokon:
            return AO::AOTypes::eCtorMudokon_52;
        case ReliveTypes::eLiftPoint:
            return AO::AOTypes::eLiftPoint_51;
        case ReliveTypes::SecurityOrb:
            return AO::AOTypes::SecurityOrb_53;
        case ReliveTypes::eMeat:
            return AO::AOTypes::eMeat_54;
        case ReliveTypes::eMeatStack:
            return AO::AOTypes::eMeatStack_55;
        case ReliveTypes::eMeatSaw:
            return AO::AOTypes::eMeatSaw_56;
        case ReliveTypes::eMine:
            return AO::AOTypes::eMine_57;
        case ReliveTypes::eRollingBallStopperShaker:
            return AO::AOTypes::eRollingBallStopperShaker_58;
        case ReliveTypes::eMotionDetector:
            return AO::AOTypes::eMotionDetector_59;
        case ReliveTypes::eRollingBallStopper:
            return AO::AOTypes::eRollingBallStopper_60;
        case ReliveTypes::ePauseMenu:
            return AO::AOTypes::ePauseMenu_61;
        case ReliveTypes::eParamite:
            return AO::AOTypes::eParamite_62;
        case ReliveTypes::eDemoPlayback:
            return AO::AOTypes::eDemoPlayback;
        case ReliveTypes::eBirdPortal:
            return AO::AOTypes::eBirdPortal_65;
        case ReliveTypes::eBirdPortalTerminator:
            return AO::AOTypes::eBirdPortalTerminator_66;
        case ReliveTypes::eFG1:
            return AO::AOTypes::eFG1_67;
        case ReliveTypes::ePullRingRope:
            return AO::AOTypes::ePullRingRope_68;
        case ReliveTypes::eAbilityRing:
            return AO::AOTypes::eAbilityRing_69;
        case ReliveTypes::eRock:
            return AO::AOTypes::eRock_70;
        case ReliveTypes::eRockSack:
            return AO::AOTypes::eRockSack_71;
        case ReliveTypes::eRollingBall:
            return AO::AOTypes::eRollingBall_72;
        case ReliveTypes::eRope:
            return AO::AOTypes::eRope_73;
        case ReliveTypes::eExplosion:
            return AO::AOTypes::eExplosion_74;
        case ReliveTypes::eMudokon:
            return AO::AOTypes::eMudokon_75;
        case ReliveTypes::eRedLaser:
            return AO::AOTypes::eRedLaser_76;
        case ReliveTypes::eScrab:
            return AO::AOTypes::eScrab_77;
        case ReliveTypes::eScreenClipper:
            return AO::AOTypes::eScreenClipper_78;
        case ReliveTypes::eEffectBase:
            return AO::AOTypes::eEffectBase_79;
        case ReliveTypes::eDeathFadeOut:
            return AO::AOTypes::eDeathFadeOut_80;
        case ReliveTypes::eFlash:
            return AO::AOTypes::eFlash_81;
        case ReliveTypes::ScreenShake:
            return AO::AOTypes::ScreenShake_82;
        case ReliveTypes::eScreenWave:
            return AO::AOTypes::eScreenWave_83;
        case ReliveTypes::eUnknown:
            return AO::AOTypes::eUnknown_84;
        case ReliveTypes::eShrykull:
            return AO::AOTypes::eShrykull_85;
        case ReliveTypes::eSnoozParticle:
            return AO::AOTypes::eSnoozParticle_87;
        case ReliveTypes::eSlig:
            return AO::AOTypes::eSlig_88;
        case ReliveTypes::eSlog:
            return AO::AOTypes::eSlog_89;
        case ReliveTypes::SlingMud:
            return AO::AOTypes::SlingMud_90;
        case ReliveTypes::eSligSpawner:
            return AO::AOTypes::eSligSpawner_91;
        case ReliveTypes::eZBall:
            return AO::AOTypes::eZBall_92;
        case ReliveTypes::eParticle:
            return AO::AOTypes::eParticle_93;
        case ReliveTypes::eZapLine:
            return AO::AOTypes::eZapLine_94;
        case ReliveTypes::eBeeSwarm:
            return AO::AOTypes::eBeeSwarm_95;
        case ReliveTypes::eBeeNest:
            return AO::AOTypes::eBeeNest_96;
        case ReliveTypes::eLever:
            return AO::AOTypes::eLever_97;
        case ReliveTypes::eTrapDoor:
            return AO::AOTypes::eTrapDoor_98;
        case ReliveTypes::eUXB:
            return AO::AOTypes::eUXB_99;
        case ReliveTypes::eMovie:
            return AO::AOTypes::eMovie_100;
        case ReliveTypes::eWell:
            return AO::AOTypes::eWell_101;
        case ReliveTypes::eCameraSwapper:
            return AO::AOTypes::eCameraSwapper_102;
        case ReliveTypes::eElectrocute:
            return AO::AOTypes::eElectrocute_103;
        default:
            ALIVE_FATAL("No relive type for this AO type");
    }
    return AO::AOTypes::eNone_0;
}

ReliveTypes IBaseGameObject::FromAE(AETypes aeType)
{
    switch (aeType)
    {
        case AETypes::eGlukkon_67:
            return ReliveTypes::eGlukkon;
    }
    return ReliveTypes::eNone;
}

AETypes IBaseGameObject::ToAE(ReliveTypes reliveType)
{
    switch (reliveType)
    {
        case ReliveTypes::eGlukkon:
            return AETypes::eGlukkon_67;
    }
    return AETypes::eNone_0;
}
