# Taken from https://nachtimwald.com/2019/10/09/python-binary-to-c-header/
# with various edits to make it work

import argparse
import sys
import os

def bin2header(data, fileName, var_name='var'):
    out = []
    out.append('#pragma once\n')
    out.append('// Generated by bin2header.py from {fileName}\n'.format(fileName=os.path.basename(fileName)))
    out.append('const unsigned char {var_name}[{dlen}] = {{'.format(var_name=var_name, dlen=len(data)))
    l = [ data[i:i+12] for i in range(0, len(data), 12) ]
    for i, x in enumerate(l):
        line = ', '.join([ '0x{val:02x}'.format(val=c) for c in x ]) # relive team: removed ord()
        out.append('  {line}{end_comma}'.format(line=line, end_comma=',' if i<len(l)-1 else ''))
    out.append('};')
    return '\n'.join(out)

def main():
    parser = argparse.ArgumentParser(description='Generate binary header output')
    parser.add_argument('-i', '--input', required=True , help='Input file')
    parser.add_argument('-o', '--out', required=True , help='Output file')
    parser.add_argument('-v', '--var', required=True , help='Variable name to use in file')

    args = parser.parse_args()
    if not args:
        return 1

    # relive team fix: needed to read as binary
    with open(args.input, 'rb') as f:
        data = f.read()

    out = bin2header(data, args.input, args.var)
    with open(args.out, 'w') as f:
        f.write(out)

    return 0

if __name__ == '__main__':
    sys.exit(main())
