
# TODO:
# - relive macOS artifacts
# - qt-editor artifacts
# - actually set BUILD_NUMBER

name: CI

on:
  push:
    branches: [beta]
  pull_request:
    branches: [beta]

# build setting(s)
env:
  CONFIGURATION: Debug

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            name: Windows32
          - os: windows-2022
            name: Windows64
          - os: ubuntu-26.04
            name: Linux
          # - os: macos-latest-large
          #   name: macOS

    steps:
    - name: Checkout repository recursively
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: 'Windows: Install SDL3'
      if: runner.os == 'Windows'
      run: |
        Invoke-WebRequest 'https://www.libsdl.org/release/SDL3-devel-3.4.14-VC.zip' -OutFile "$env:GITHUB_WORKSPACE\SDL3.zip"
        7z x SDL3.zip

    # ======================================
    #      Windows32
    # ======================================

    - name: 'Windows32: Install Qt 5.15.2'
      if: runner.os == 'Windows'
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        arch: 'win32_msvc2019'

    - name: 'Windows32: Build'
      if: matrix.name == 'Windows32'
      run: |
        mkdir build
        cd build
        cmake .. -G"Visual Studio 17 2022" -DSDL3_DIR="$env:GITHUB_WORKSPACE\SDL3-3.4.14\cmake" -DCMAKE_PREFIX_PATH="$env:QT_ROOT_DIR" -A Win32 -DCI_PROVIDER="GitHub" -DBUILD_NUMBER="$env:GITHUB_RUN_NUMBER"
        cmake --build . --config $env:CONFIGURATION
        cpack -G ZIP -C $env:CONFIGURATION

    # ======================================
    #      Windows64
    # ======================================

    - name: 'Windows64: Install Qt 5.15.2'
      if: runner.os == 'Windows'
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        arch: 'win64_msvc2019_64'

    - name: 'Windows64: Build'
      if: matrix.name == 'Windows64'
      run: |
        mkdir build
        cd build
        cmake .. -G"Visual Studio 17 2022" -DSDL3_DIR="$env:GITHUB_WORKSPACE\SDL3-3.4.14\cmake" -DCMAKE_PREFIX_PATH="$env:QT_ROOT_DIR" -A x64 -DCI_PROVIDER="GitHub" -DBUILD_NUMBER="$env:GITHUB_RUN_NUMBER"
        cmake --build . --config $env:CONFIGURATION
        cpack -G ZIP -C $env:CONFIGURATION
        
    # ======================================
    #      Linux
    # ======================================

    - name: 'Linux: Install SDL3'
      if: matrix.name == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl3-dev

    - name: 'Linux: Install Qt 5.15.2'
      if: matrix.name == 'Linux'
      uses: jurplel/install-qt-action@v4
      with:
        version: '5.15.2'
        arch: 'gcc_64'

    - name: 'Linux: Build'
      if: matrix.name == 'Linux'
      run: |
        mkdir build
        cd build
        cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=$CONFIGURATION -DCI_PROVIDER="GitHub" -DBUILD_NUMBER=$GITHUB_RUN_NUMBER
        make -j$(nproc)
        cmake --build . --target appimage

    # ======================================
    #      macOS
    # ======================================

    # - name: 'macOS: Install Qt 5.15.2'
    #   if: matrix.name == 'macOS'
    #   uses: jurplel/install-qt-action@v4
    #   with:
    #     version: '5.15.2'
    #     arch: 'clang_64'

    # - name: 'macOS: Install SDL2, moltenvk'
    #   if: matrix.name == 'macOS'
    #   run: |
    #     brew install sdl2 molten-vk

    # TODO: mac artifacts
    # mkdir Frameworks
    # cp /usr/local/lib/libSDL2.dylib ./Frameworks/libSDL2.dylib
    # cp /usr/local/lib/libMoltenVK.dylib ./Frameworks/libMoltenVK.dylib
    # cpack -G DragNDrop

    # - name: 'macOS: Build'
    #   if: matrix.name == 'macOS'
    #   run: |
    #     mkdir build
    #     cd build
    #     cmake .. -G"Unix Makefiles" -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_BUILD_TYPE=$CONFIGURATION -DCMAKE_PREFIX_PATH=$(brew --prefix qt@5) -DCI_PROVIDER="GitHub" -DBUILD_NUMBER=$GITHUB_RUN_NUMBER
    #     make -j4

    # ======================================
    #      Artifacts
    # ======================================

    - name: 'Windows: Upload relive binaries'
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}-${{ env.CONFIGURATION }}-relive-binaries
        path: |
          build\Source\relive\${{ env.CONFIGURATION }}\relive.exe
          build\Source\relive\${{ env.CONFIGURATION }}\SDL3.dll

    - name: 'Windows: Upload relive symbols'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}-${{ env.CONFIGURATION }}-relive-symbols
        path: build\Source\relive\${{ env.CONFIGURATION }}\relive.pdb

    - name: 'Linux: Upload relive AppImage'
      if: matrix.name == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}-${{ env.CONFIGURATION }}-relive.AppImage
        path: build/relive-x86_64.AppImage

   # - name: 'macOS: Upload relive dmg'
   #   if: matrix.name == 'macOS'
   #   uses: actions/upload-artifact@v4
   #   with:
   #     name: ${{ matrix.name }}-${{ env.CONFIGURATION }}-relive.dmg
   #     path: build/relive-0.1-Darwin.dmg